name: CherrySkyPVP
version: '${project.version}'
main: net.cherrycraft.cherryskypvp.CherrySkyPVP
api-version: '1.20'
commands:
  setspawn:
    description: Sets the spawn point for the world
  coins:
    description: Shows your current coins
  bounty:
    description: Shows your current bounty
  kit:
    description: Shows your current kit
