name: ReefRealmSkyPVP
version: '${project.version}'
main: net.reefrealm.reefrealmskypvp.ReefRealmSkyPVP
api-version: '1.20'
commands:
  setspawn:
    description: Sets the spawn point for the world
  coins:
    description: Shows your current coins
  bounty:
    description: Shows your current bounty
